/**
 * Languages are taken from: http://www.iana.org/assignments/language-subtag-registry/language-subtag-registry
 * Native names of the languages are taken from: https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes
 */
export class Languages {
	aa= 'Afaraf'; // Afar
	ab= 'аҧсуа бызшәа, аҧсшәа'; // Abkhazian
	ae= 'avesta'; // Avestan
	af= 'Afrikaans'; // Afrikaans
	ak= 'Akan'; // Akan
	am= 'አማርኛ'; // Amharic
	an= 'aragonés'; // Aragonese
	ar= 'العربية'; // Arabic
	as= 'অসমীয়া'; // Assamese
	av= 'авар мацӀ, магӀарул мацӀ'; // Avaric
	ay= 'aymar aru'; // Aymara
	az= 'azərbaycan dili'; // Azerbaijani
	ba= 'башҡорт теле'; // Bashkir
	be= 'беларуская мова'; // Belarusian
	bg= 'български език'; // Bulgarian
	bh= 'भोजपुरी'; // Bihari languages
	bi= 'Bislama'; // Bislama
	bm= 'bamanankan'; // Bambara
	bn= 'বাংলা'; // Bengali/Bangla
	bo= 'བོད་ཡིག'; // Tibetan
	br= 'brezhoneg'; // Breton
	bs= 'bosanski jezik'; // Bosnian
	ca= 'català, valencià'; // Catalan/Valencian
	ce= 'нохчийн мотт'; // Chechen
	ch= 'Chamoru'; // Chamorro
	co= 'corsu, lingua corsa'; // Corsican
	cr= 'ᓀᐦᐃᔭᐍᐏᐣ'; // Cree
	cs= 'čeština, český jazyk'; // Czech
	cu= 'ѩзыкъ словѣньскъ'; // Church Slavic/Church Slavonic/Old Bulgarian/Old Church Slavonic/Old Slavonic
	cv= 'чӑваш чӗлхи'; // Chuvash
	cy= 'Cymraeg'; // Welsh
	da= 'dansk'; // Danish
	de= 'Deutsch'; // German
	dv= 'ދިވެހި'; // Dhivehi/Divehi/Maldivian
	dz= 'རྫོང་ཁ'; // Dzongkha
	ee= 'Eʋegbe'; // Ewe
	el= 'ελληνικά'; // Greek (modern)
	en= 'English'; // English
	eo= 'Esperanto'; // Esperanto
	es= 'Español'; // Spanish/Castilian
	et= 'eesti, eesti keel'; // Estonian
	eu= 'euskara, euskera'; // Basque
	fa= 'فارسی'; // Persian
	ff= 'Fulfulde, Pulaar, Pular'; // Fulah
	fi= 'suomi, suomen kieli'; // Finnish
	fj= 'vosa Vakaviti'; // Fijian
	fo= 'føroyskt'; // Faroese
	fr= 'français, langue française'; // French
	fy= 'Frysk'; // Western Frisian
	ga= 'Gaeilge'; // Irish
	gd= 'Gàidhlig'; // Scottish Gaelic/Gaelic
	gl= 'Galego'; // Galician
	gn= 'Avañe\'ẽ'; // Guarani
	gu= 'ગુજરાતી'; // Gujarati
	gv= 'Gaelg, Gailck'; // Manx
	ha= 'هَوُسَ'; // Hausa
	he= 'עברית'; // Hebrew (modern)
	hi= 'हिन्दी, हिंदी'; // Hindi
	ho= 'Hiri Motu'; // Hiri Motu
	hr= 'hrvatski jezik'; // Croatian
	ht= 'Kreyòl ayisyen'; // Haitian/Haitian Creole
	hu= 'magyar'; // Hungarian
	hy= 'Հայերեն'; // Armenian
	hz= 'Otjiherero'; // Herero
	ia= 'Interlingua'; // (International Auxiliary Language Association)
	id= 'Bahasa Indonesia'; // Indonesian
	ie= 'Interlingue (Occidental)';
	ig= 'Asụsụ Igbo'; // Igbo
	ii= 'ꆈꌠ꒿ Nuosuhxop'; // Sichuan Yi, Nuosu
	ik= 'Iñupiaq, Iñupiatun'; // Inupiaq
	io= 'Ido'; // Ido
	is= 'Íslenska'; // Icelandic
	it= 'Italiano'; // Italian
	iu= 'ᐃᓄᒃᑎᑐᑦ'; // Inuktitut
	ja= '日本語 (にほんご)'; // Japanese
	jv= 'ꦧꦱꦗꦮ, Basa Jawa'; // Javanese
	ka= 'ქართული'; // Georgian
	kg= 'Kikongo'; // Kongo
	ki= 'Gĩkũyũ'; // Kikuyu/Gikuyu
	kj= 'Kuanyama'; // Kuanyama/Kwanyama
	kk= 'қазақ тілі'; // Kazakh
	kl= 'kalaallisut, kalaallit oqaasii'; // Kalaallisut/Greenlandic
	km= 'ខ្មែរ, ខេមរភាសា, ភាសាខ្មែរ'; // Central Khmer
	kn= 'ಕನ್ನಡ'; // Kannada
	ko= '한국어'; // Korean
	kr= 'Kanuri'; // Kanuri
	ks= 'कश्मीरी, كشميري‎'; // Kashmiri
	ku= 'Kurdî, كوردی'; // Kurdish
	kv= 'коми кыв'; // Komi
	kw= 'Kernewek'; // Cornish
	ky= 'Кыргызча, Кыргыз тили'; // Kirghiz, Kyrgyz
	la= 'latine, lingua latina'; // Latin
	lb= 'Lëtzebuergesch'; // Luxembourgish, Letzeburgesch
	lg= 'Luganda'; // Ganda
	li= 'Limburgs'; // Limburgan, Limburger, Limburgish
	ln= 'Lingála'; // Lingala
	lo= 'ພາສາລາວ'; // Lao
	lt= 'lietuvių kalba'; // Lithuanian
	lu= 'Kiluba'; // Luba-Katanga
	lv= 'Latviešu Valoda'; // Latvian
	mg= 'fiteny malagasy'; // Malagasy
	mh= 'Kajin M̧ajeļ'; // Marshallese
	mi= 'te reo Māori'; // Maori
	mk= 'македонски јазик'; // Macedonian
	ml= 'മലയാളം'; // Malayalam
	mn= 'Монгол хэл'; // Mongolian
	mr= 'मराठी'; // Marathi
	ms= 'Bahasa Melayu, بهاس ملايو‎'; // Malay
	mt= 'Malti'; // Maltese
	my= 'ဗမာစာ'; // Burmese
	na= 'Dorerin Naoero'; // Nauru
	nb= 'Norsk Bokmål'; // Norwegian Bokmål
	nd= 'isiNdebele'; // North Ndebele
	ne= 'नेपाली'; // Nepali
	ng= 'Owambo'; // Ndonga
	nl= 'Nederlands, Vlaams'; // Dutch, Flemish
	nn= 'Norsk Nynorsk'; // Norwegian Nynorsk
	no= 'Norsk'; // Norwegian
	nr= 'isiNdebele'; // South Ndebele
	nv= 'Diné bizaad'; // Navajo, Navaho
	ny= 'chiCheŵa, chinyanja'; // Nyanja, Chewa, Chichewa
	oc= 'occitan, lenga d\'òc'; // Occitan
	oj= 'ᐊᓂᔑᓈᐯᒧᐎᓐ'; // Ojibwa
	om= 'Afaan Oromoo'; // Oromo
	or= 'ଓଡ଼ିଆ'; // Oriya
	os= 'ирон æвзаг'; // Ossetian, Ossetic
	pa= 'ਪੰਜਾਬੀ'; // Panjabi, Punjabi
	pi= 'पाऴि'; // Pali
	pl= 'Język Polski, Polszczyzna'; // Polish
	ps= 'پښتو'; // Pushto, Pashto
	pt= 'Português'; // Portuguese
	qu= 'Runa Simi, Kichwa'; // Quechua
	rm= 'Rumantsch Grischun'; // Romansh
	rn= 'Ikirundi'; // Rundi
	ro= 'Română'; // Romanian, Moldavian, Moldovan
	ru= 'Русский'; // Russian
	rw= 'Ikinyarwanda'; // Kinyarwanda
	sa= 'संस्कृतम्'; // Sanskrit
	sc= 'sardu'; // Sardinian
	sd= 'सिन्धी, سنڌي، سندھی'; // Sindhi
	se= 'Davvisámegiella'; // Northern Sami
	sg= 'yângâ tî sängö'; // Sango
	si= 'සිංහල'; // Sinhala, Sinhalese
	sk= 'Slovenčina, Slovenský Jazyk'; // Slovak
	sl= 'Slovenski Jezik, Slovenščina'; // Slovenian
	sm= 'gagana fa\'a Samoa'; // Samoan
	sn= 'chiShona'; // Shona
	so= 'Soomaaliga, af Soomaali'; // Somali
	sq= 'Shqip'; // Albanian
	sr= 'српски језик'; // Serbian
	ss= 'SiSwati'; // Swati
	st= 'Sesotho'; // Southern Sotho
	su= 'Basa Sunda'; // Sundanese
	sv= 'Svenska'; // Swedish
	sw= 'Kiswahili'; // Swahili
	ta= 'தமிழ்'; // Tamil
	te= 'తెలుగు'; // Telugu
	tg= 'тоҷикӣ, toçikī, تاجیکی‎'; // Tajik
	th= 'ไทย'; // Thai
	ti= 'ትግርኛ'; // Tigrinya
	tk= 'Türkmen, Түркмен'; // Turkmen
	tl= 'Wikang Tagalog'; // Tagalog
	tn= 'Setswana'; // Tswana
	to= 'Faka Tonga'; // Tonga (Tonga Islands)
	tr= 'Türkçe'; // Turkish
	ts= 'Xitsonga'; // Tsonga
	tt= 'татар теле, tatar tele'; // Tatar
	tw= 'Twi'; // Twi
	ty= 'Reo Tahiti'; // Tahitian
	ug= 'ئۇيغۇرچە‎, Uyghurche'; // Uighur, Uyghur
	uk= 'Українська'; // Ukrainian
	ur= 'اردو'; // Urdu
	uz= 'Oʻzbek, Ўзбек, أۇزبېك‎'; // Uzbek
	ve= 'Tshivenḓa'; // Venda
	vi= 'Tiếng Việt'; // Vietnamese
	vo= 'Volapük'; // Volapük
	wa= 'Walon'; // Walloon
	wo= 'Wollof'; // Wolof
	xh= 'isiXhosa'; // Xhosa
	yi= 'ייִדיש'; // Yiddish
	yo= 'Yorùbá'; // Yoruba
	za= 'Saɯ cueŋƅ, Saw cuengh'; // Zhuang Chuang
	zh= '中文 (Zhōngwén), 汉语, 漢語'; // Chinese
	zu= 'isiZulu'; // Zulu
}
